"""added specialization

Revision ID: 4e511f40432c
Revises: 4801960b2b4f
Create Date: 2024-06-13 12:33:58.152495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e511f40432c'
down_revision: Union[str, None] = '4801960b2b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('specialization', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'specialization')
    # ### end Alembic commands ###
